config/routes.rb
Rails
  .application
  .routes
  .draw do
    root 'foods#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    get 'logout', to: 'user_sessions#destroy'
    delete 'logout', to: 'user_sessions#destroy'
    get '/guest_login', to: 'user_sessions#guest_login'
    post '/guest_login', to: 'user_sessions#guest_login'

    resources :users, only: %i[index new create show]

    resources :mymenus
    resources :foods
    resources :eatdate_likes, only: %i[create destroy]
    resources :rankings, only: %i[index]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/views/shared/_footer.html.slim
.w-full.h-14.md:hidden.block
  section#bottom-navigation.fixed.inset-x-0.bottom-0.z-10.bg-white.shadow
    #tabs.flex.justify-between
      = link_to root_path, class: "w-full focus:text-teal-500 hover:text-gray-200 inline justify-center inline-block text-center pt-2 pb-1 text-blue-500"
        i.fas.fa-home.fa-2x
        span.block.text-xs トップページ
      = link_to new_food_path, 'data-turbolinks': false, class: "w-full focus:text-teal-500 hover:text-gray-200 inline justify-center inline-block text-center pt-2 pb-1 text-yellow-500"
        .flex.flex-col.relative.items-center
          i.fas.fa-utensils.fa-2x
          -if @tutorial
            span.balloon2.md:hidden.whitespace-nowrap ここをタップ！
        span.block.text-xs 食事の記録
      = link_to rankings_path, class: "w-full focus:text-teal-500 hover:text-gray-200 inline justify-center inline-block text-center pt-2 pb-1 text-green-500"
        i.fas.fa-list-alt.fa-2x.my-auto
        span.block.text-xs ランキング
      a.w-full.text-gray-500.inline.hover:text-gray-200.inline.justify-center.inline-block.text-center.pt-2.pb-1 href="#" 
        i.fas.fa-cog.fa-2x.my-auto
        span.block.text-xs 設定

app/views/shared/_header.html.slim
.w-full.h-16
  header.h-16.px-3.5.bg-white.dark:bg-gray-800.border-solid.border-2.border-light-blue-500.shadow
    .h-full.md:mx-14.flex.justify-between.items-center.px-3.md:px-0
      = link_to 'Food Sharey', root_path, class: "h-full flex items-center text-2xl font-bold text-cyan-600 dark:text-cyan-500"
      .flex.items-center.h-full.text-gray-500.dark:text-gray-300.relative
        - if logged_in?
          = link_to  'ランキング一覧', rankings_path, class: "hidden md:block mr-3 flex items-center shadow border-green-500 border-2 rounded-full px-4 py-2 md:text-green-500 text-white bg-green-500 md:bg-white hover:bg-green-500 hover:text-white"
          = link_to '食事を記録する', new_food_path, 'data-turbolinks': false, class: "hidden md:block mr-3 flex items-center shadow border-yellow-500 border-2 rounded-full px-4 py-2 md:text-yellow-500 text-white bg-yellow-500 md:bg-white hover:bg-yellow-500 hover:text-white"
          -if @tutorial
            .balloon1.hidden.md:block ここをクリック！
          = link_to 'ログアウト', logout_path, method: :delete, class: "flex items-center shadow border-blue-500 border-2 rounded-full px-4 py-2 text-blue-500 hover:bg-blue-500 hover:text-white"
        - else
          / = link_to '新規登録', new_user_path, class: "mr-3 flex items-center shadow border-blue-500 border-2 rounded-full px-4 py-2 text-blue-500 hover:bg-blue-500 hover:text-white"
          / = link_to 'ログイン', login_path, class: "flex items-center shadow border-blue-500 border-2 rounded-full px-4 py-2 text-blue-500 hover:bg-blue-500 hover:text-white"

app/views/shared/_notifications.html.slim
.notification.sticky.inset-x-0.top-0.z-10
  .notice 
  - flash.each do |key, value|
    = content_tag :div, value, class: key