config/routes.rb
Rails
  .application
  .routes
  .draw do
    root 'foods#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    get 'logout', to: 'user_sessions#destroy'
    delete 'logout', to: 'user_sessions#destroy'
    get '/guest_login', to: 'user_sessions#guest_login'
    post '/guest_login', to: 'user_sessions#guest_login'

    resources :users, only: %i[index new create show]

    resources :mymenus
    resources :foods
    resources :eatdate_likes, only: %i[create destroy]
    resources :rankings, only: %i[index]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :eatdate
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  skip_before_action :require_login, only: [:index]
  def index
    require "date"
    @date = Time.now
    if (Time.parse("03:00")..Time.parse("09:59")).cover? @date
      @ranking = Eatdate.where(timezone: 1).includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
      @menu = "人気の朝食メニュー"
    elsif (Time.parse("10:00")..Time.parse("14:59")).cover? @date
      @ranking = Eatdate.where(timezone: 2).includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
      @menu = "人気の昼食メニュー"
    elsif (Time.parse("15:00")..Time.parse("23:59")).cover? @date or (Time.parse("00:00")..Time.parse("02:59")).cover? @date
      @ranking = Eatdate.where(timezone: 4).includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
      @menu = "人気の夕食メニュー"
    end
    @eatdate = Array.new
    @ranking.each do |ranking|
      if Food.find_by(eatdate_id: ranking)
        @eatdate.push(ranking)
      end
      if logged_in?
        break if @eatdate.length == 10
      else
        break if @eatdate.length == 8
      end
    end
    if logged_in?
      @morning_id = Eatdate.find_by(date: @date,timezone: 1 , user_id: current_user.id)
      @lunch_id = Eatdate.find_by(date: @date,timezone: 2 , user_id: current_user.id)
      @dinner_id = Eatdate.find_by(date: @date,timezone: 4 , user_id: current_user.id)
      @morning_foods = Food.where(eatdate_id: @morning_id)
      @lunch_foods = Food.where(eatdate_id: @lunch_id)
      @dinner_foods = Food.where(eatdate_id: @dinner_id)
      @tutorial = 'ようこそ！まずは記録ボタンから食事内容を記録しましょう' if !Eatdate.find_by(user_id: current_user.id)
    end
  end

  def new
    if params[:date].present? && params[:time].present?
      @date = Time.parse(params[:date])
      @timezone = params[:time]
    else
      @date = Time.now.to_date
      if (Time.parse("03:00")..Time.parse("10:59")).cover? @date
        @timezone = "朝食"
      elsif (Time.parse("11:00")..Time.parse("14:59")).cover? @date
        @timezone = "昼食"
      elsif (Time.parse("15:00")..Time.parse("16:59")).cover? @date
        @timezone = "間食"
      elsif (Time.parse("17:00")..Time.parse("23:59")).cover? @date
        @timezone = "夕食"
      elsif (Time.parse("00:00")..Time.parse("02:59")).cover? @date
        @timezone = "夜食"
      end
    end
    @mymenu = Mymenu.where(user_id: current_user.id).order("id ASC")
    @eatdate = Eatdate.find_by(date: @date,timezone: @timezone , user_id: current_user.id)
    @morning_id = Eatdate.find_by(date: @date,timezone: 1 , user_id: current_user.id)
    @lunch_id = Eatdate.find_by(date: @date,timezone: 2 , user_id: current_user.id)
    @snack_id = Eatdate.find_by(date: @date,timezone: 3 , user_id: current_user.id)
    @dinner_id = Eatdate.find_by(date: @date,timezone: 4 , user_id: current_user.id)
    @supper_id = Eatdate.find_by(date: @date,timezone: 5 , user_id: current_user.id)
    @morning_foods = Food.where(eatdate_id: @morning_id)
    @morning_calorie = @morning_foods.sum(:calorie)
    @lunch_foods = Food.where(eatdate_id: @lunch_id)
    @lunch_calorie = @lunch_foods.sum(:calorie)
    @snack_foods = Food.where(eatdate_id: @snack_id)
    @snack_calorie = @snack_foods.sum(:calorie)
    @dinner_foods = Food.where(eatdate_id: @dinner_id)
    @dinner_calorie = @dinner_foods.sum(:calorie)
    @supper_foods = Food.where(eatdate_id: @supper_id)
    @supper_calorie = @supper_foods.sum(:calorie)
    if !Mymenu.find_by(user_id: current_user.id) && !Eatdate.find_by(user_id: current_user.id)
      @tutorial1 = 'まずはMYメニューを作成してメニューを登録しましょう'
    elsif !Eatdate.find_by(user_id: current_user.id)
      @tutorial2 = '登録ができたら上の食事時刻を食事を行った日時に設定し、下の登録したメニューから食事内容を記録しましょう'
    elsif session[:tutorial3]
      @tutorial3 = session[:tutorial3]
      session.delete(:tutorial3)
    end
  end

  def create
    params[:timezone] = params[:eatdate][:timezone]
    @eatdate = Eatdate.find_by(date: params[:date], timezone: params[:timezone], user_id: current_user.id)
    if !Eatdate.find_by(user_id: current_user.id)
      session[:tutorial3] = '下のリストに食事記録が反映されました！食事習慣を続けていきましょう'
    end
    @eatdate.present? ? @eatdate.update(eat_time: params[:eat_time],comment: params[:comment]) : @eatdate = Eatdate.create!(eatdate_params)
    if params[:mymenu_id].present? && @food = Food.find_by(eatdate_id: @eatdate.id, mymenu_id: params[:mymenu_id])
      @food.delete
    elsif params[:mymenu_id].present?
      @mymenu = Mymenu.find(params[:mymenu_id])
      Food.create!(name: @mymenu.name, image: @mymenu.image.url, calorie: @mymenu.calorie, protein: @mymenu.protein, fat: @mymenu.fat, carbohydrate: @mymenu.carbohydrate, sugar: @mymenu.sugar, dietary_fiber: @mymenu.dietary_fiber, salt: @mymenu.salt, Vitamin_A: @mymenu.Vitamin_A, Vitamin_D: @mymenu.Vitamin_D, Vitamin_E: @mymenu.Vitamin_E, Vitamin_B1: @mymenu.Vitamin_B1, Vitamin_B2: @mymenu.Vitamin_B2, Vitamin_B6: @mymenu.Vitamin_B6, Vitamin_B12: @mymenu.Vitamin_B12, Vitamin_C: @mymenu.Vitamin_C, potassium: @mymenu.potassium, calcium: @mymenu.calcium, magnesium: @mymenu.magnesium, iron: @mymenu.iron, eatdate_id: @eatdate.id, mymenu_id: @mymenu.id)
    end
    redirect_to new_food_path(date: params[:date], time: params[:timezone])
    return
  end

  def edit
  end

  def update
  end

  def destroy
    @food = Food.find_by_id(params[:id])
    if @food && @food.eatdate.user_id == current_user.id
      @food.delete
      redirect_to new_food_path(date: params[:date], time: params[:time])
    else
      redirect_to root_path
    end
  end

  private
  def eatdate_params
    params.permit(:date, :timezone, :eat_time, :comment).merge(user_id: current_user.id)
  end

  def food_params
    params.permit(:name, :image, :calorie, :protein, :fat, :carbohydrate, :sugar, :dietary_fiber, :salt, :Vitamin_A, :Vitamin_D, :Vitamin_E, :Vitamin_B1, :Vitamin_B2, :Vitamin_B6, :Vitamin_B12, :Vitamin_C, :potassium, :calcium, :magnesium, :iron, :eatdate_id)
  end
end

app/views/foods/_todayEatdata.html.slim
.notification
  .notice #{@tutorial}
.px-3.bg-white.dark:bg-gray-800.my-10.w-full
  .md:mx-14.px-3.md:px-0.flex.flex-col.lg:flex-row.flex-col-reverse
    .mt-10.lg:mr-14.lg:mt-0
      .px-4.py-3.text-center.text-base.font-medium.text-white.rounded-t-xl.bg-green-400.whitespace-nowrap
        span #{@menu}
      ul.divide-y.divide-gray-200.border.shadow-lg.rounded-b-xl.lg:w-72
        - @eatdate.each do |eatdate|
          li.focus:outline-none.hover:bg-gray-50.text-gray-600.hover:text-gray-800
            a[href="#"]
              .p-3.flex.flex-col
                .flex.flex-row.mb-2
                  span.text-sm.tracking-wide.truncate.mr-auto
                    | #{eatdate.user.name}さん
                  - if eatdate.foods.pluck(:calorie).map!{|x| x.to_i}.sum != 0
                    span.px-2.leading-relaxed.mr-2.text-xs.font-medium.tracking-wide.text-indigo-500.bg-indigo-50.rounded-full
                      | #{eatdate.foods.pluck(:calorie).map!{|x| x.to_i}.sum}kcal
                  span id="js-like-button-#{eatdate.id}"
                    = render 'eatdate_likes/like', eatdate: eatdate
                .flex.gap-x-3
                  - eatdate.foods.pluck(:image).each do |image|
                    - if image.present?
                      = image_tag image, class: "h-10 w-10 inline-block"
                    - else
                      = image_tag "l_e_others_501.png", class: "h-10 w-10 inline-block"
        li.focus:outline-none
          .p-3.text-right
            = link_to rankings_path, class: "py-1 px-2 inline-block no-underline border-b-2 border-transparent tracking-wide shadow border-green-500 border-2 rounded-full text-green-500 hover:bg-green-500 hover:text-white"
              | ランキング一覧
    .p-3.bg-white.rounded-xl.shadow-lg.w-full.pb-10
      .grid.gap-8.grid-cols-1
        .flex.flex-col.md:flex-row.items-center
          h1.block.w-full.text-center.text-green-400.text-2xl.font-bold.mb-6
            | 本日の食事内容
        .flex.flex-col.lg:flex-row.gap-y-5
          .px-3.5.w-full
            = link_to new_food_path(date: @date.strftime("%Y-%m-%d"), time: "朝食")
              .px-6.py-3.flex.justify-around.text-base.font-medium.text-white.rounded-t-xl.bg-green-400
                |  朝食
            ul.py-4.space-y-5.border.shadow-lg.rounded-b-xl
              - if @morning_foods.present?
                - @morning_foods.first(7).each do |morning_food|
                  li
                    a.relative.flex.flex-row.items-center.h-11.focus:outline-none.hover:bg-gray-50.text-gray-600.hover:text-gray-800.border-l-4.border-transparent.hover:border-indigo-500.pr-6[href="#"]
                      span.inline-flex.justify-center.items-center.ml-4
                        - if morning_food.image.present?
                          = image_tag(morning_food.image, size: "50x50", alt: "")
                        - else
                          = image_tag "l_e_others_501.png", class: "h-10 w-10"
                      span.ml-2.text-sm.tracking-wide.truncate
                        = morning_food.name
                - if @morning_foods.count >= 8
                  li
                    = link_to new_food_path(date: @date.strftime("%Y-%m-%d"), time: "朝食"), class: "flex justify-end focus:outline-none text-gray-600 hover:text-gray-800 border-l-4 border-transparent pr-6"
                      span.ml-2.text-sm.tracking-wide.truncate.text-indigo-500
                        | もっと見る
          .px-3.5.w-full
            = link_to new_food_path(date: @date.strftime("%Y-%m-%d"), time: "昼食")
              .px-6.py-3.flex.justify-around.text-base.font-medium.text-white.rounded-t-xl.bg-green-400
                |  昼食
            ul.py-4.space-y-5.border.shadow-lg.rounded-b-xl
              - if @lunch_foods.present?
                - @lunch_foods.first(7).each do |lunch_food|
                  li
                    a.relative.flex.flex-row.items-center.h-11.focus:outline-none.hover:bg-gray-50.text-gray-600.hover:text-gray-800.border-l-4.border-transparent.hover:border-indigo-500.pr-6[href="#"]
                      span.inline-flex.justify-center.items-center.ml-4
                        - if lunch_food.image.present?
                          = image_tag(lunch_food.image, size: "50x50", alt: "")
                        - else
                          = image_tag "l_e_others_501.png", class: "h-10 w-10"
                      span.ml-2.text-sm.tracking-wide.truncate
                        = lunch_food.name
                - if @lunch_foods.count >= 8
                  li
                    = link_to new_food_path(date: @date.strftime("%Y-%m-%d"), time: "昼食"), class: "flex justify-end focus:outline-none text-gray-600 hover:text-gray-800 border-l-4 border-transparent pr-6"
                      span.ml-2.text-sm.tracking-wide.truncate.text-indigo-500
                        | もっと見る
          .px-3.5.w-full
            = link_to new_food_path(date: @date.strftime("%Y-%m-%d"), time: "夕食")
              .px-6.py-3.flex.justify-around.text-base.font-medium.text-white.rounded-t-xl.bg-green-400
                |  夕食
            ul.py-4.space-y-5.border.shadow-lg.rounded-b-xl
              - if @dinner_foods.present?
                - @dinner_foods.first(7).each do |dinner_food|
                  li
                    a.relative.flex.flex-row.items-center.h-11.focus:outline-none.hover:bg-gray-50.text-gray-600.hover:text-gray-800.border-l-4.border-transparent.hover:border-indigo-500.pr-6[href="#"]
                      span.inline-flex.justify-center.items-center.ml-4
                        - if dinner_food.image.present?
                          = image_tag(dinner_food.image, size: "50x50", alt: "")
                        - else
                          = image_tag "l_e_others_501.png", class: "h-10 w-10"
                      span.ml-2.text-sm.tracking-wide.truncate
                        = dinner_food.name
                - if @dinner_foods.count >= 8
                  li
                    = link_to new_food_path(date: @date.strftime("%Y-%m-%d"), time: "夕食"), class: "flex justify-end focus:outline-none text-gray-600 hover:text-gray-800 border-l-4 border-transparent pr-6"
                      span.ml-2.text-sm.tracking-wide.truncate.text-indigo-500
                        | もっと見る

app/views/foods/_topImage.html.slim
.relative.flex.flex-col-reverse.py-16.lg:pt-0.lg:flex-col.lg:pb-0
  .inset-y-0.top-0.right-0.z-0.w-full.max-w-xl.px-4.mx-auto.md:px-0.lg:pr-0.lg:mb-0.lg:mx-0.lg:w-7/12.lg:max-w-full.lg:absolute.xl:px-0
    svg.absolute.left-0.hidden.h-full.text-white.transform.-translate-x-1/2.lg:block[viewbox="0 0 100 100" fill="currentColor" preserveaspectratio="none slice"]
      path[d="M50 0H100L50 100H0L50 0Z"]
    = image_tag "B82B4BC0-BC6D-4DA5-AAB9-11F883CCB72F.jpg", class: "object-cover w-full h-56 rounded shadow-lg lg:rounded-none lg:shadow-none md:h-96 lg:h-full"
  .relative.flex.flex-col.items-start.w-full.max-w-xl.px-4.mx-auto.md:px-0.lg:px-8.lg:max-w-screen-xl
    .mb-16.lg:my-40.lg:max-w-lg.lg:pr-5
      h2.mb-5.text-center.font-sans.text-3xl.font-bold.tracking-tight.text-gray-900.sm:text-4xl.sm:leading-none
        |  よりよい食生活を送るための
        br.hidden.md:block
        |  食事管理アプリ
      p.pr-5.mb-5.text-center.text-base.text-gray-700.md:text-lg
        |  日々の食事を記録して、
        br
        | 食事内容をユーザー同士で共有することができる食事管理アプリです
      .flex.items-center.justify-around
        = link_to '新規登録', new_user_path, class: "mr-3 flex items-center shadow border-blue-500 border-2 rounded-full  px-4 py-2 text-blue-500 hover:bg-blue-500 hover:text-white"
        = link_to 'ログイン', login_path, class: "flex items-center shadow border-blue-500 border-2 rounded-full  px-4 py-2 text-blue-500 hover:bg-blue-500 hover:text-white"
      .flex.items-center.justify-around.mt-5
        = link_to "お試しログイン", guest_login_path, method: :post, class:"flex items-center shadow border-yellow-500 border-2 rounded-full  px-4 py-2 text-yellow-500 hover:bg-yellow-500 hover:text-white"
.bg-white.dark:bg-gray-800.mt-6.lg:mt-16.w-full[class="px-3.5"]
  .md:mx-14.flex.flex-col
    h1.hidden.md:block.w-full.text-center.text-green-400.text-4xl.xl:text-3xl.font-bold
      | #{@menu}
    .mt-6.lg:mt-10.md:hidden
      .px-6.py-3.text-center.text-base.font-medium.text-white.rounded-t-xl.md:rounded-xl.bg-green-400.whitespace-nowrap
        | #{@menu}
    section.text-gray-600.body-font.md:block.hidden
      .container.pt-8
        .flex.flex-wrap.-m-4
          - @eatdate.each do |eatdate|
            .p-4.xl:w-1/4.lg:w-1/3.md:w-1/2
              .border-2.border-gray-200.border-opacity-60.rounded-lg.overflow-hidden
                .w-1/2.h-48.w-full.object-center.flex.flex-wrap.gap-y-4.gap-x-2.md:gap-x-4.lg:gap-1.items-center.p-4.xl:px-1[class="lg:px-2.5 md:px-3"]
                  - eatdate.foods.pluck(:image).each_with_index do |image, i|
                    - if i < 6
                      - if image.present?
                        - if eatdate.foods.length == 1
                          = image_tag image, class: "h-44 w-44 inline-block mx-auto"
                        - elsif eatdate.foods.length == 2
                          = image_tag image, class: "h-28 w-28 inline-block mx-auto"
                        - else
                          = image_tag image, class: "md:h-20 md:w-20 h-24 w-24 inline-block"
                      - else
                        - if eatdate.foods.length == 1
                          = image_tag "l_e_others_501.png", class: "h-44 w-44 inline-block mx-auto"
                        - elsif eatdate.foods.length == 2
                          = image_tag "l_e_others_501.png", class: "h-28 w-28 inline-block mx-auto"
                        - else
                          = image_tag "l_e_others_501.png", class: "md:h-20 md:w-20 h-24 w-24 inline-block"
                .p-4
                  h1.title-font.text-lg.font-medium.text-gray-900.mb-3
                    | #{eatdate.user.name}さん
                  .flex.items-center.flex-wrap.justify-end
                    a.text-indigo-500.inline-flex.items-center.md:mb-2.lg:mb-0.mr-auto
                      | Learn More
                      svg.w-4.h-4.ml-2[viewbox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"]
                        path[d="M5 12h14"]
                        path[d="M12 5l7 7-7 7"]
                    - if eatdate.foods.pluck(:calorie).map!{|x| x.to_i}.sum != 0
                      span.px-2.leading-relaxed.mr-2.text-xs.font-medium.tracking-wide.text-indigo-500.bg-indigo-50.rounded-full
                        | #{eatdate.foods.pluck(:calorie).map!{|x| x.to_i}.sum}kcal
                    span id="js-like-button-#{eatdate.id}"
                      = render 'eatdate_likes/like', eatdate: eatdate
    ul.divide-y.divide-gray-200.border.shadow-lg.rounded-b-xl.md:hidden.block
      - @eatdate.each do |eatdate|
        li.focus:outline-none.hover:bg-gray-50.text-gray-600.hover:text-gray-800
          .p-3.flex.flex-col
            .flex.flex-row
              span.text-sm.tracking-wide.truncate.mr-auto
                | #{eatdate.user.name}さん
              - if eatdate.foods.pluck(:calorie).map!{|x| x.to_i}.sum != 0
                span.px-2.leading-relaxed.mr-2.text-xs.font-medium.tracking-wide.text-indigo-500.bg-indigo-50.rounded-full
                  | #{eatdate.foods.pluck(:calorie).map!{|x| x.to_i}.sum}kcal
              span id="js-like-button-0#{eatdate.id}"
                = render 'eatdate_likes/like', eatdate: eatdate
            .flex.gap-x-3
              - eatdate.foods.pluck(:image).each_with_index do |image, i|
                - if i < 6
                  - if image.present?
                    = image_tag image, class: "h-10 w-10 inline-block"
                  - else
                    = image_tag "l_e_others_501.png", class: "h-10 w-10 inline-block"