config/routes.rb
Rails
  .application
  .routes
  .draw do
    root 'foods#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    get 'logout', to: 'user_sessions#destroy'
    delete 'logout', to: 'user_sessions#destroy'
    get '/guest_login', to: 'user_sessions#guest_login'
    post '/guest_login', to: 'user_sessions#guest_login'

    resources :users, only: %i[index new create show]

    resources :mymenus
    resources :foods
    resources :eatdate_likes, only: %i[create destroy]
    resources :rankings, only: %i[index]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/eatdate_like.rb
class EatdateLike < ApplicationRecord
  belongs_to :eatdate
  belongs_to :user
end

app/controllers/eatdate_likes_controller.rb
class EatdateLikesController < ApplicationController
  def create
    EatdateLike.create!(like_params)
    @eatdate = Eatdate.find(params[:eatdate_id])
  end

  def destroy
    EatdateLike.find_by(eatdate_id: params[:id], user_id: current_user.id).delete
    @eatdate = Eatdate.find(params[:id])
  end

  private


  def like_params
    params.permit(:eatdate_id).merge(user_id: current_user.id)
  end

end

app/views/eatdate_likes/_like.html.slim
- if logged_in?
  - if eatdate.eatdate_likes.find_by(eatdate_id: eatdate.id,user_id: current_user)
    = button_to eatdate_like_path(eatdate.id), remote: true, method: :delete, id: "js-like-button", class: "no-underline border-b-2 border-transparent tracking-wide flex flex-row shadow border-pink-500 border-2 rounded-full px-2 text-pink-500 hover:bg-pink-500 hover:text-white"
      i.fas.fa-heart.fa-1x.my-auto
      span.inline.ml-1
        | #{eatdate.eatdate_likes.count}
  - else
    = button_to eatdate_likes_path(eatdate_id: eatdate.id), remote: true, method: :post, id: "js-like-button", class: "no-underline border-b-2 border-transparent tracking-wide flex flex-row shadow border-pink-500 border-2 rounded-full px-2 text-pink-500 hover:bg-pink-500 hover:text-white"
      i.far.fa-heart.fa-1x.my-auto
      span.inline.ml-1
        | #{eatdate.eatdate_likes.count}
- else
  .no-underline.border-b-2.border-transparent.tracking-wide.flex.flex-row.shadow.border-pink-500.border-2.rounded-full.px-2.text-pink-500.cursor-not-allowed
    i.far.fa-heart.fa-1x.my-auto
    span.inline.ml-1
      | #{eatdate.eatdate_likes.count}

app/views/eatdate_likes/create.js.slim
| document.getElementById('js-like-button-#{@eatdate.id}').innerHTML = "#{j(render 'eatdate_likes/like', eatdate: @eatdate)}";
  document.getElementById('js-like-button-0#{@eatdate.id}').innerHTML = "#{j(render 'eatdate_likes/like', eatdate: @eatdate)}";

app/views/eatdate_likes/destroy.js.slim
| document.getElementById('js-like-button-#{@eatdate.id}').innerHTML = "#{j(render 'eatdate_likes/like', eatdate: @eatdate)}";
  document.getElementById('js-like-button-0#{@eatdate.id}').innerHTML = "#{j(render 'eatdate_likes/like', eatdate: @eatdate)}";